import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { doc, getDoc } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { auth } from "./auth.js";
import { db } from "./firebase.js";
import { approveProviderRequest, getPendingProviderRequests, rejectProviderRequest } from "./services/provider-requests-service.js";
import { addRegionAdmin, addTownAdmin, getAllProvidersAdmin, getAllRegionsAdmin, getAllTownsAdmin, updateProviderAdmin, updateRegionAdmin, updateTownAdmin } from "./services/admin-data-service.js";
import { closeReportAdmin, getReportsAdmin } from "./services/reports-service.js";

const $=s=>document.querySelector(s), loginForm=$("#login-form"), dashboard=$("#dashboard"), loginStatus=$("#login-status");
let currentAdmin=null, pendingRequests=[], reports=[], providers=[], regions=[], towns=[], selectedRegion="";
const make=(tag,className,text)=>{const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;};
const button=(text,className,handler)=>{const el=make("button",className,text);el.type="button";el.addEventListener("click",handler);return el;};
const field=(label,value)=>{const el=make("div");el.append(make("span",null,label),make("strong",null,value||"—"));return el;};

document.querySelectorAll(".admin-tab").forEach(tab=>tab.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(x=>x.classList.toggle("active",x===tab));document.querySelectorAll(".admin-panel").forEach(x=>x.classList.toggle("hidden",x.id!==tab.dataset.panel));if(tab.dataset.panel==="reports-panel"){reports.length?renderReports():loadReports();}if(tab.dataset.panel==="providers-panel"){providers.length?renderProviders():loadProviders();}if(tab.dataset.panel==="locations-panel"){regions.length?renderLocations():loadLocations();}}));
document.querySelectorAll("[data-refresh]").forEach(x=>x.addEventListener("click",loadRequests));

async function labelRequest(item){const refs=[doc(db,"regions",item.regionId),doc(db,"towns",item.townId),doc(db,"categories",item.categoryId),doc(db,"specialties",item.specialtyIds[0])];const [region,town,category,specialty]=await Promise.all(refs.map(x=>getDoc(x)));return {...item,placeLabel:`${town.data()?.nameAr||item.townId}، ${region.data()?.nameAr||item.regionId}`,categoryLabel:category.data()?.nameAr||item.categoryId,specialtyLabel:specialty.data()?.nameAr||item.specialtyIds[0]};}
async function loadRequests(){const list=$("#requests");list.replaceChildren(make("div","notice","جارٍ تحميل الطلبات…"));try{const items=await getPendingProviderRequests();pendingRequests=await Promise.all(items.map(labelRequest));renderFilteredRequests();}catch(error){console.error(error);list.replaceChildren(make("div","notice notice-error","تعذر تحميل الطلبات."));}}
function renderFilteredRequests(){const term=$("#request-search").value.trim().toLocaleLowerCase("ar"),items=pendingRequests.filter(x=>`${x.name} ${x.phone||""} ${x.address||""} ${x.placeLabel||""}`.toLocaleLowerCase("ar").includes(term));renderRequests(items);}
function renderRequests(items){const list=$("#requests");list.replaceChildren();$("#request-count").textContent=`${items.length} من أصل ${pendingRequests.length} طلب`;$("#requests-badge").textContent=pendingRequests.length;$("#stat-requests").textContent=pendingRequests.length;if(!items.length){list.append(make("div","notice",pendingRequests.length?"لا توجد نتائج مطابقة.":"لا توجد طلبات جديدة حالياً."));return;}items.forEach(item=>{const card=make("article","request-card"),head=make("div","request-head"),meta=make("div","request-meta"),actions=make("div","request-actions");head.append(make("h2",null,item.name),make("span","status-pill","قيد المراجعة"));meta.append(field("الهاتف",item.phone),field("واتساب",item.whatsapp),field("العنوان",item.address),field("المكان",item.placeLabel),field("الفئة",item.categoryLabel),field("الاختصاص",item.specialtyLabel));actions.append(button("قبول ونشر","secondary-button",()=>review(item.id,"approve")),button("رفض","danger-button",()=>review(item.id,"reject")));card.append(head,meta,make("p","request-description",item.description||"لا يوجد وصف إضافي."),actions);list.append(card);});}
async function review(id,decision){if(!confirm(decision==="approve"?"هل تريد قبول هذا الطلب ونشر مقدم الخدمة؟":"هل تريد رفض هذا الطلب؟"))return;try{decision==="approve"?await approveProviderRequest(id,currentAdmin.uid):await rejectProviderRequest(id,currentAdmin.uid);await Promise.all([loadRequests(),loadStats()]);}catch(error){console.error(error);alert("تعذر تنفيذ القرار.");}}
$("#request-search").addEventListener("input",renderFilteredRequests);

async function loadReports(){const list=$("#reports-admin-list");list.replaceChildren(make("div","notice","جارٍ تحميل البلاغات…"));try{reports=(await getReportsAdmin()).filter(x=>x.status==="open");renderReports();}catch(error){console.error(error);list.replaceChildren(make("div","notice notice-error","تعذر تحميل البلاغات."));}}
function renderReports(){const labels={incorrect:"معلومات خاطئة",closed:"خدمة متوقفة",abuse:"إساءة أو نشاط مشبوه",privacy:"طلب خصوصية",other:"موضوع آخر"},list=$("#reports-admin-list");list.replaceChildren();$("#reports-count").textContent=`${reports.length} بلاغ مفتوح`;$("#reports-badge").textContent=reports.length;if(!reports.length){list.append(make("div","notice","لا توجد بلاغات مفتوحة."));return;}reports.forEach(item=>{const card=make("article","request-card"),head=make("div","request-head"),meta=make("div","request-meta"),actions=make("div","request-actions");head.append(make("h2",null,labels[item.type]||"بلاغ"),make("span","status-pill","مفتوح"));meta.append(field("الاسم",item.reporterName),field("التواصل",item.contact),field("الرابط",item.pageUrl));actions.append(button("تمت المعالجة","secondary-button",async()=>{try{await closeReportAdmin(item.id,currentAdmin.uid);reports=reports.filter(x=>x.id!==item.id);renderReports();}catch{alert("تعذر إغلاق البلاغ.");}}));card.append(head,meta,make("p","request-description",item.details),actions);list.append(card);});}

async function loadProviders(){const list=$("#providers-admin-list");list.replaceChildren(make("div","notice","جارٍ تحميل مقدمي الخدمات…"));try{providers=await getAllProvidersAdmin();renderProviders();}catch(error){console.error(error);list.replaceChildren(make("div","notice notice-error","تعذر تحميل مقدمي الخدمات."));}}
async function loadStats(){try{const [providerItems,regionItems,townItems]=await Promise.all([getAllProvidersAdmin(),getAllRegionsAdmin(),getAllTownsAdmin()]);providers=providerItems;regions=regionItems;towns=townItems;$("#stat-providers").textContent=providers.length;$("#stat-active").textContent=providers.filter(x=>x.isActive).length;$("#stat-locations").textContent=`${regions.length} / ${towns.length}`;}catch(error){console.error(error);}}
function renderProviders(){const term=$("#provider-search").value.trim().toLocaleLowerCase("ar"),items=providers.filter(x=>`${x.name} ${x.phone||""}`.toLocaleLowerCase("ar").includes(term)),list=$("#providers-admin-list");list.replaceChildren();$("#providers-count").textContent=`${items.length} من أصل ${providers.length}`;if(!items.length){list.append(make("div","notice","لا توجد نتائج."));return;}items.forEach(item=>{const card=make("article","admin-item"),copy=make("div","admin-item-copy"),badges=make("div","item-badges"),actions=make("div","item-actions");badges.append(make("span",item.isActive?"active-pill":"inactive-pill",item.isActive?"منشور":"معطّل"));if(item.isVerified)badges.append(make("span","verified-badge","موثّق"));copy.append(make("strong",null,item.name),make("span",null,`${item.phone||"لا يوجد هاتف"} · ${item.address||"لا يوجد عنوان"}`),badges);actions.append(button("تعديل","plain-button",()=>editProvider(item)),button(item.isVerified?"إلغاء التوثيق":"توثيق","plain-button",()=>toggleProvider(item,"isVerified")),button(item.isActive?"تعطيل":"تفعيل",item.isActive?"danger-button":"secondary-button",()=>toggleProvider(item,"isActive")));card.append(copy,actions);list.append(card);});}
async function toggleProvider(item,key){try{await updateProviderAdmin(item.id,{[key]:!item[key]});item[key]=!item[key];renderProviders();}catch(error){console.error(error);alert("تعذر حفظ التغيير.");}}
async function editProvider(item){const name=prompt("اسم مقدم الخدمة",item.name);if(name===null||!name.trim())return;const phone=prompt("رقم الهاتف",item.phone||"");if(phone===null)return;const address=prompt("العنوان",item.address||"");if(address===null)return;try{await updateProviderAdmin(item.id,{name:name.trim(),phone:phone.trim(),address:address.trim()});Object.assign(item,{name:name.trim(),phone:phone.trim(),address:address.trim()});providers.sort((a,b)=>a.name.localeCompare(b.name,"ar"));renderProviders();}catch(error){console.error(error);alert("تعذر تعديل مقدم الخدمة.");}}
$("#provider-search").addEventListener("input",renderProviders);

async function loadLocations(){try{[regions,towns]=await Promise.all([getAllRegionsAdmin(),getAllTownsAdmin()]);selectedRegion=selectedRegion||regions[0]?.id||"";renderLocations();}catch(error){console.error(error);$("#regions-admin-list").replaceChildren(make("div","notice notice-error","تعذر تحميل المناطق والبلدات."));}}
function renderLocations(){const select=$("#town-region");select.replaceChildren(new Option("اختر المنطقة",""));regions.forEach(x=>select.add(new Option(x.nameAr,x.id)));const regionList=$("#regions-admin-list");regionList.replaceChildren();regions.forEach(item=>{const row=make("div",`compact-item ${item.id===selectedRegion?"selected":""}`),pick=button(item.nameAr,"compact-name",()=>{selectedRegion=item.id;renderLocations();}),actions=make("div","mini-actions");pick.append(make("small",null,item.nameEn));actions.append(button("تعديل","text-button",()=>editRegion(item)),button(item.isActive?"تعطيل":"تفعيل","text-button",()=>toggleRegion(item)));row.append(pick,actions);regionList.append(row);});const active=regions.find(x=>x.id===selectedRegion),townList=$("#towns-admin-list");$("#towns-title").textContent=active?`بلدات ${active.nameAr}`:"البلدات";townList.replaceChildren();const filtered=towns.filter(x=>x.regionId===selectedRegion);if(!filtered.length)townList.append(make("div","notice","لا توجد بلدات في هذه المنطقة."));filtered.forEach(item=>{const row=make("div","compact-item"),copy=make("div","compact-copy"),actions=make("div","mini-actions");copy.append(make("strong",null,item.nameAr),make("small",null,item.nameEn));actions.append(button("تعديل","text-button",()=>editTown(item)),button(item.isActive?"تعطيل":"تفعيل","text-button",()=>toggleTown(item)));row.append(copy,actions);townList.append(row);});}
async function editRegion(item){const nameAr=prompt("اسم المنطقة بالعربية",item.nameAr);if(nameAr===null||!nameAr.trim())return;const nameEn=prompt("اسم المنطقة بالإنجليزية",item.nameEn||"");if(nameEn===null)return;try{await updateRegionAdmin(item.id,{nameAr:nameAr.trim(),nameEn:nameEn.trim()});Object.assign(item,{nameAr:nameAr.trim(),nameEn:nameEn.trim()});renderLocations();}catch{alert("تعذر تعديل المنطقة.");}}
async function toggleRegion(item){try{await updateRegionAdmin(item.id,{isActive:!item.isActive});item.isActive=!item.isActive;renderLocations();}catch{alert("تعذر حفظ التغيير.");}}
async function editTown(item){const nameAr=prompt("اسم البلدة بالعربية",item.nameAr);if(nameAr===null||!nameAr.trim())return;const nameEn=prompt("اسم البلدة بالإنجليزية",item.nameEn||"");if(nameEn===null)return;try{await updateTownAdmin(item.id,{nameAr:nameAr.trim(),nameEn:nameEn.trim(),legacyKey:nameEn.trim()});Object.assign(item,{nameAr:nameAr.trim(),nameEn:nameEn.trim()});renderLocations();}catch{alert("تعذر تعديل البلدة.");}}
async function toggleTown(item){try{await updateTownAdmin(item.id,{isActive:!item.isActive});item.isActive=!item.isActive;renderLocations();}catch{alert("تعذر حفظ التغيير.");}}
$("#region-form").addEventListener("submit",async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{await addRegionAdmin({nameAr:$("#region-name-ar").value,nameEn:$("#region-name-en").value});event.target.reset();await loadLocations();}catch{alert("تعذر إضافة المنطقة.");}finally{submit.disabled=false;}});
$("#town-form").addEventListener("submit",async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{await addTownAdmin({regionId:$("#town-region").value,nameAr:$("#town-name-ar").value,nameEn:$("#town-name-en").value});event.target.reset();await loadLocations();}catch{alert("تعذر إضافة البلدة.");}finally{submit.disabled=false;}});

loginForm.addEventListener("submit",async event=>{event.preventDefault();loginStatus.textContent="جارٍ تسجيل الدخول…";try{await signInWithEmailAndPassword(auth,$("#email").value,$("#password").value);}catch(error){console.error(error);loginStatus.textContent="بيانات الدخول غير صحيحة أو طريقة Email/Password غير مفعّلة.";}});
$("#logout").addEventListener("click",()=>signOut(auth));
onAuthStateChanged(auth,async user=>{if(!user){currentAdmin=null;dashboard.classList.add("hidden");loginForm.classList.remove("hidden");return;}try{const admin=await getDoc(doc(db,"admins",user.uid));if(!admin.exists()||admin.data().isActive!==true){loginStatus.textContent="هذا الحساب لا يملك صلاحية الإدارة.";await signOut(auth);return;}currentAdmin=user;loginForm.classList.add("hidden");dashboard.classList.remove("hidden");$("#admin-email").textContent=user.email;await Promise.all([loadRequests(),loadReports(),loadStats()]);}catch(error){console.error(error);loginStatus.textContent="تعذر التحقق من صلاحية الإدارة.";await signOut(auth);}});
